version: '3'
services:
  backend:
    image: golang:1.16.5-alpine
    ports:
      - "8080:8080"
    build: ./backend
  frontend:
    image: node:14-alpine
    ports:
      - "5000:5000"
    build: ./project
    depends_on:
      - backend